x-airflow-common: &airflow-common
  build: 
    context: .
    dockerfile: Dockerfile
  environment: &airflow-common-env
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql://airflow:airflow@mysql:3306/airflow
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: false
    AIRFLOW__CORE__FERNET_KEY: '填入FERNET_KEY'
    AIRFLOW__WEBSERVER__SECRET_KEY: '填入WEBSERVER__SECRET_KEY'
    AIRFLOW__CORE__ALLOW_FUTURE_EXEC_DATES: 'True'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'
    AIRFLOW__WEBSERVER__INSTANCE_NAME: 'GCP Airflow'
    AIRFLOW__WEBSERVER__AUTHENTICATE: 'True'
    AIRFLOW__WEBSERVER__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW__WEBSERVER__BASE_URL: '外部IP:端口'
    AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: 'True'
    AIRFLOW__WEBSERVER__PROXY_FIX_X_FOR: 1
    AIRFLOW__WEBSERVER__PROXY_FIX_X_PROTO: 1
    AIRFLOW__WEBSERVER__PROXY_FIX_X_HOST: 1
    AIRFLOW__WEBSERVER__PROXY_FIX_X_PORT: 1
    AIRFLOW__WEBSERVER__PROXY_FIX_X_PREFIX: 1
    AIRFLOW__WEBSERVER__WEB_SERVER_HOST: '0.0.0.0'
    AIRFLOW__WEBSERVER__WEB_SERVER_PORT: '端口'
    AIRFLOW__WEBSERVER__COOKIE_SECURE: 'False'
    AIRFLOW__WEBSERVER__COOKIE_SAMESITE: 'Lax'
    AIRFLOW_HOME: /opt/airflow
    PYTHONPATH: /opt/airflow
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:- mysqlclient apache-airflow[mysql]}
    AIRFLOW_UID: "${AIRFLOW_UID:-50000}"
    AIRFLOW_GID: "${AIRFLOW_GID:-0}"
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./config:/opt/airflow/config
    - ./plugins:/opt/airflow/plugins
  networks:
    - airflow_network

services:
  mysql:
    image: mysql:8.0
    container_name: financial_project-mysql
    networks:
      - airflow_network
    environment:
      - MYSQL_ROOT_PASSWORD=[ROOT密碼]
      - MYSQL_USER=[airflow使用MYSQL帳號]
      - MYSQL_PASSWORD=[airflow使用MYSQL密碼]
      - MYSQL_DATABASE=[database名稱]
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "MYSQL端口:MYSQL端口"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "airflow", "-pairflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  webserver:
    <<: *airflow-common
    container_name: financial_project-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: webserver
    ports:
      - "AIRFLOW端口:AIRFLOW端口"
    environment:
      <<: *airflow-common-env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  scheduler:
    <<: *airflow-common
    container_name: financial_project-scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: scheduler
    restart: always

  airflow-init:
    <<: *airflow-common
    container_name: financial_project-airflow-init
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: /bin/bash
    command: |
      -c '
      while ! nc -z mysql 3306; do
        echo "Waiting for MySQL to be ready..."
        sleep 5
      done
      
      airflow db migrate
      airflow db upgrade
      
      airflow users list | grep -q "admin" || \
      airflow users create \
        --username AIRFLOW帳號 \
        --password AIRFLOW密碼 \
        --role Admin \
        --email admin@example.com
      
      echo "Initialization completed successfully"
      '

networks:
  airflow_network:
    name: airflow_network
    driver: bridge

volumes:
  mysql_data:
    name: financial_project_mysql_data
